# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c01e34814f9d65f359d7a0a8f5157b2caac88563e8ba03cab78b1a91ec22e4a6ba1ae1082df731dc3198368a99a7c96f67e38baae85028b96e6cde50e02a670d

test:
  secret_key_base: 18141ac20ece13a562812b8944f92be7101ecb54d275605bedee3ef57cda96bb59771de43fa137b109b418b7f8d43188eb755eabda17bbe6df42e0e5b91355ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
